name: Github Pages

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout starter
        uses: actions/checkout@v2

      - name: Checkout notablog
        uses: actions/checkout@v2
        with:
          repository: PatrickG1014/notablog
          path: notablog

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Build notablog
        run: |
          cd notablog
          npm install
          npm run build:module
          npm install -g .

      - name: Build site
        run: notablog generate .
